---
title: "Religious Identity"
author: "Connair J. S. Russell"
number-depth: 2
---

## Measure

## Implementation

`rid_02 only appears if rid_01 = Yes`

+-------------+------------------------------------------------------------------------------------------+------------------------------------------------------+
| Qlabel      | Question                                                                                 | Response options                                     |
+=============+==========================================================================================+======================================================+
| rid_01      | Do you regard yourself as belonging to a particular religion?                            | Yes/No                                               |
+-------------+------------------------------------------------------------------------------------------+------------------------------------------------------+
| rid_02      | If yes, which?                                                                           | 1.  Protestant                                       |
|             |                                                                                          |                                                      |
|             |                                                                                          | 2.  Catholic                                         |
|             |                                                                                          |                                                      |
|             |                                                                                          | 3.  Orthodox (e.g. Greek Orthodox, Russian Orthodox) |
|             |                                                                                          |                                                      |
|             |                                                                                          | 4.  Sunni                                            |
|             |                                                                                          |                                                      |
|             |                                                                                          | 5.  Shiite                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 6.  Buddhist                                         |
|             |                                                                                          |                                                      |
|             |                                                                                          | 7.  Confucian                                        |
|             |                                                                                          |                                                      |
|             |                                                                                          | 8.  Daoist                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 9.  Hindu                                            |
|             |                                                                                          |                                                      |
|             |                                                                                          | 10. Jewish                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 11. Shinto                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 12. Other (please specify)                           |
+-------------+------------------------------------------------------------------------------------------+------------------------------------------------------+
| rid_03      | Whilst growing up did your primary caregiver belong to a particular religion?            | Yes/No                                               |
+-------------+------------------------------------------------------------------------------------------+------------------------------------------------------+
| rid_04      | If yes, which?                                                                           | 1.  Protestant                                       |
|             |                                                                                          |                                                      |
|             |                                                                                          | 2.  Catholic                                         |
|             |                                                                                          |                                                      |
|             |                                                                                          | 3.  Orthodox (e.g. Greek Orthodox, Russian Orthodox) |
|             |                                                                                          |                                                      |
|             |                                                                                          | 4.  Sunni                                            |
|             |                                                                                          |                                                      |
|             |                                                                                          | 5.  Shiite                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 6.  Buddhist                                         |
|             |                                                                                          |                                                      |
|             |                                                                                          | 7.  Confucian                                        |
|             |                                                                                          |                                                      |
|             |                                                                                          | 8.  Daoist                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 9.  Hindu                                            |
|             |                                                                                          |                                                      |
|             |                                                                                          | 10. Jewish                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 11. Shinto                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 12. Other (please specify)                           |
+-------------+------------------------------------------------------------------------------------------+------------------------------------------------------+
| rid_05      | Whilst growing up did an additional important caregiver belong to a particular religion? | Yes/No                                               |
+-------------+------------------------------------------------------------------------------------------+------------------------------------------------------+
| rid_06      | If yes, which?                                                                           | 1.  Protestant                                       |
|             |                                                                                          |                                                      |
|             |                                                                                          | 2.  Catholic                                         |
|             |                                                                                          |                                                      |
|             |                                                                                          | 3.  Orthodox (e.g. Greek Orthodox, Russian Orthodox) |
|             |                                                                                          |                                                      |
|             |                                                                                          | 4.  Sunni                                            |
|             |                                                                                          |                                                      |
|             |                                                                                          | 5.  Shiite                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 6.  Buddhist                                         |
|             |                                                                                          |                                                      |
|             |                                                                                          | 7.  Confucian                                        |
|             |                                                                                          |                                                      |
|             |                                                                                          | 8.  Daoist                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 9.  Hindu                                            |
|             |                                                                                          |                                                      |
|             |                                                                                          | 10. Jewish                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 11. Shinto                                           |
|             |                                                                                          |                                                      |
|             |                                                                                          | 12. Other (please specify)                           |
+-------------+------------------------------------------------------------------------------------------+------------------------------------------------------+

### Scoring/ Coding

See the Belief Measures landing page for all belief measures variables and their definitions.

## 
